"use client";

import { GraduationCap, Stethoscope, CircleSlash, HeartHandshake } from "lucide-react";
import LegalPage, { type LegalSection } from "@/components/legal-page";

interface TermsViewProps {
  onBack: () => void;
}

const SECTIONS: LegalSection[] = [
  {
    icon: GraduationCap,
    title: "Educational Purpose",
    body: (
      <>
        <p>
          PlainHealth is provided as an educational tool that translates
          medical language into plain English. It is built to improve health
          literacy and to help you feel more confident reading your own
          medical documents.
        </p>
        <p>
          By using PlainHealth you acknowledge that the service is intended
          for learning and general understanding, not for clinical
          decision-making.
        </p>
      </>
    ),
  },
  {
    icon: Stethoscope,
    title: "Not Medical Advice",
    body: (
      <p>
        Nothing generated by PlainHealth constitutes medical advice, diagnosis,
        or treatment recommendation. The explanations are simplifications
        produced by an AI language model and have not been reviewed by a
        licensed clinician. They should never replace the judgement of a
        qualified healthcare professional who knows your full medical history.
      </p>
    ),
    tint: "bg-red-50 text-red-700",
  },
  {
    icon: CircleSlash,
    title: "No Guarantee of Accuracy",
    body: (
      <>
        <p>
          While we work to keep explanations clear and helpful, PlainHealth
          makes no warranty regarding accuracy, completeness, or
          timeliness. Language models can misread shorthand, confuse similar
          terms, or fail to surface clinically relevant context.
        </p>
        <p>
          Always cross-check anything that matters against the original
          document and with a healthcare professional.
        </p>
      </>
    ),
  },
  {
    icon: HeartHandshake,
    title: "Consult Qualified Healthcare Professionals",
    body: (
      <>
        <p>
          If you have a question about what a result, prescription, or note
          means for you specifically, ask your doctor, pharmacist, or another
          qualified clinician. They can interpret it in the context of your
          health history, medications, and symptoms.
        </p>
        <p>
          If you are experiencing a medical emergency, contact your local
          emergency services immediately.
        </p>
      </>
    ),
  },
];

export default function TermsView({ onBack }: TermsViewProps) {
  return (
    <LegalPage
      eyebrow="Terms"
      title="How to use PlainHealth responsibly."
      lead="PlainHealth is a focused educational tool. These short terms explain what it is, what it isn't, and how to use it well."
      sections={SECTIONS}
      onBack={onBack}
    />
  );
}
